import type { Metadata } from 'next'
import Header from '@/components/Dashboard/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={""}>
      <div className={"min-h-screen flex items-center justify-center text-[100px]"}>
        {children}
      </div>
      </body>
    </html>
  )
}
